version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.3
    steps:
      - checkout
      - run:
          name: Install Ruby dependencies
          command: |
            bundle install --path vendor/bundle
      - run: cat /proc/version
      - run:
          name: ldd
          command: |
            ldd /home/circleci/project/vendor/bundle/ruby/2.4.0/gems/mini_racer-0.1.15/lib/mini_racer_extension.so
      - run:
          name: objdump
          command: |
            objdump --syms /home/circleci/project/vendor/bundle/ruby/2.4.0/gems/mini_racer-0.1.15/lib/mini_racer_extension.so | grep _ZN2v82V813InitializeICUEPKc
      - run:
          name: Try mini_racer
          command: |
            bundle exec ruby try_mini_racer.rb
